miProyecto/fennys/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Rutas inicio
    path('', views.index, name='index'),
    
    # Rutas de productos
    path('productos/', views.productos, name='productos'),
    path('productos/categoria/<int:categoria_id>/', views.filtrar_por_categoria, name='filtrar_por_categoria'),
    path('productos/<int:producto_id>/', views.detalle_producto, name='detalle_producto'),
    path('lista_productos/', views.lista_productos, name='lista_productos'),

    # Rutas de usuarios
    path('contacto/', views.contacto, name='contacto'),
    path('agregar/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('registro/', views.registro, name='registro'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('ver_perfil/', views.ver_perfil, name='ver_perfil'),
    path('editar_perfil/<int:user_id>/', views.editar_perfil, name='editar_perfil'),
    path('cambiar_clave/', views.cambiar_clave, name='cambiar_clave'),

    # Rutas de carrito
    path('cancelar_producto/<int:producto_id>/', views.cancelar_producto, name='cancelar_producto'),
    path('pagar/', views.pagar, name='pagar'),
    path('cancelar_pedido/<int:pedido_id>/', views.cancelar_pedido, name='cancelar_pedido'),
    path('cambiar_cantidad/<int:producto_id>/', views.cambiar_cantidad, name='cambiar_cantidad'),
    path('carrito/', views.ver_carrito, name='ver_carrito'),
    path('eliminar_producto/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('borrar_todo/', views.borrar_todo, name='borrar_todo'),
    path('cancelar_todo/', views.cancelar_todo, name='cancelar_todo'),
]

miProyecto/miProyecto/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fennys.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miProyecto/fennys/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.contrib.auth.models import AbstractUser

from .authentication import CustomUserManager
import uuid


from io import BytesIO
from django.core.files import File
import json

from django.utils import timezone

# Definición de los roles para los usuarios
class Role(models.TextChoices):
    ADMIN = 'Admin', 'Admin'
    TENDER = 'Tendero', 'Tendero'
    CLIENT = 'Cliente', 'Cliente'

# Modelo de Usuario personalizado
class Usuario(models.Model):
    rol = models.CharField(
        max_length=10,
        choices=Role.choices,
        default=Role.CLIENT,
    )
    estado = models.BooleanField(default=True)
    foto = models.ImageField(upload_to='usuarios/', null=True, blank=True)
    token_recuperar = models.CharField(max_length=255, null=True, blank=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    cedula = models.CharField(max_length=20, null=True, blank=True)  # Añadir el campo cedula

    def __str__(self):
        return self.nombre
# Modelo de Categoría de productos
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    foto = models.ImageField(upload_to='categorias/', null=True, blank=True)

    def __str__(self):
        return self.nombre

# Modelo de Producto
class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=0)
    inventario = models.IntegerField()
    categoria = models.ForeignKey(Categoria, related_name='productos', on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='productos/', null=True, blank=True)

    def __str__(self):
        return self.nombre

# Modelo de Pedido
class Pedido(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)  # Agregar esta línea
    fecha = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    cantidad_total = models.IntegerField(default=0)  # Nuevo campo para contar productos

    def __str__(self):
        return f"Pedido {self.id} - Total: {self.total}"
    
# Modelo de Detalle del Pedido
class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    @property
    def subtotal(self):
        return self.cantidad * self.precio

miProyecto/fennys/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from .crypt import hash_password, verify_password
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny
from django.core.mail import send_mail
from django.conf import settings



def index(request):
    productos = Producto.objects.all()
    
    # Obtener el carrito de la sesión
    carrito = request.session.get('carrito', {})

    # Calcular el total del carrito
    total_carrito = 0
    cantidad_total = 0
    for item in carrito.values():
        total_carrito += int(item['cantidad']) * float(item['precio'])
        cantidad_total += int(item['cantidad'])

    return render(request, 'fennys/index.html', {
        'productos': productos,
        'carrito': carrito,
        'total_carrito': total_carrito,
        'cantidad_total': cantidad_total  # Pasar la cantidad total al contexto
    })

def productos(request):
    productos = Producto.objects.all()
    categorias = Categoria.objects.all()

    # Obtener el carrito de la sesión
    carrito = request.session.get('carrito', {})

    # Calcular el total del carrito
    total_carrito = 0
    cantidad_total = sum(item['cantidad'] for item in carrito.values())

    return render(request, 'fennys/productos/productos.html', {
        'productos': productos,
        'categorias': categorias,
        'cantidad_total': cantidad_total  # Pasar la cantidad total al contexto
    })


def contacto(request):
    if request.method == 'POST':
        # Recibir los datos del formulario
        nombre = request.POST.get('nombre')
        correo = request.POST.get('correo')
        mensaje = request.POST.get('mensaje')
        tipo_mensaje = request.POST.get('tipo_mensaje')

        # Definir el asunto con el tipo de mensaje
        asunto = f"{tipo_mensaje}: Nuevo mensaje de contacto de {nombre}"

        # Definir el color para el cuerpo del correo
        if tipo_mensaje == 'Exigencia':
            color = 'orange'
        elif tipo_mensaje == 'Reclamo':
            color = 'red'
        elif tipo_mensaje == 'Felicitación':
            color = 'green'
        elif tipo_mensaje == 'Sugerencia':
            color = 'blue'
        else:
            color = 'black'

        # Validar que todos los campos estén llenos
        if nombre and correo and mensaje:
            try:
                # Crear el mensaje con el correo del usuario incluido y color en el mensaje
                mensaje_correo = f"""
                    <p><strong>De:</strong> {nombre} &lt;{correo}&gt;</p>
                    <p><strong>Mensaje:</strong></p>
                    <p style="color:{color};">{mensaje}</p>
                """

                # Enviar el correo al administrador (a tu correo)
                send_mail(
                    asunto,
                    '',  # El cuerpo en blanco (ya lo pondremos en el HTML)
                    correo,  # El correo del que envía
                    [settings.CONTACT_EMAIL],  # Correo al que se enviará el mensaje
                    fail_silently=False,
                    html_message=mensaje_correo  # Esto permite el envío de HTML en el correo
                )

                # Mensaje de éxito
                messages.success(request, '¡Gracias por tu mensaje! Nos pondremos en contacto pronto.')
                return redirect('contacto')  # Redirige a la vista de contacto
            except Exception as e:
                # Si ocurre un error en el envío del correo
                messages.error(request, 'Hubo un error al enviar tu mensaje. Intenta nuevamente.')
                return redirect('contacto')
        else:
            # Si falta algún campo
            messages.error(request, 'Por favor, llena todos los campos correctamente.')
            return redirect('contacto')
    else:
        # Obtener el carrito de la sesión
        carrito = request.session.get('carrito', {})

        # Calcular el total del carrito
        total_carrito = 0
        cantidad_total = 0
        for item in carrito.values():
            total_carrito += int(item['cantidad']) * float(item['precio'])
            cantidad_total += int(item['cantidad'])

        # Si la solicitud es GET, solo se muestra el formulario vacío
        return render(request, 'fennys/contacto/contacto.html', {
            'carrito': carrito,
            'total_carrito': total_carrito,
            'cantidad_total': cantidad_total  # Pasar la cantidad total al contexto
        })


def lista_productos(request):
    # Obtener todas las categorías para el filtro
    categorias = Categoria.objects.all()
    categoria_id = request.GET.get('categoria')

    # Filtrar productos según la categoría seleccionada
    if categoria_id:
        productos = Producto.objects.filter(categoria_id=categoria_id)
        categoria_seleccionada = get_object_or_404(Categoria, id=categoria_id)
    else:
        productos = Producto.objects.all()
        categoria_seleccionada = None

    # Obtener el carrito de la sesión
    carrito = request.session.get('carrito', {})

    # Calcular el total del carrito
    total_carrito = 0
    for item in carrito.values():
        total_carrito += int(item['cantidad']) * float(item['precio'])

    # Calcular la cantidad total de productos en el carrito
    cantidad_total = sum(item['cantidad'] for item in carrito.values())

    return render(request, 'fennys/productos/lista_productos.html', {
        'productos': productos,
        'categorias': categorias,
        'categoria_seleccionada': categoria_seleccionada,
        'carrito': carrito,
        'total_carrito': total_carrito,
        'cantidad_total': cantidad_total  # Pasar la cantidad total al contexto
    })

def agregar_al_carrito(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)

    # Inicializar el carrito en la sesión si no existe
    if 'carrito' not in request.session:
        request.session['carrito'] = {}

    # Verificar el inventario
    if producto.inventario <= 0:
        messages.warning(request, f"{producto.nombre} está agotado.")
        return redirect('lista_productos')

    # Agregar el producto al carrito
    if str(producto.id) in request.session['carrito']:
        request.session['carrito'][str(producto.id)]['cantidad'] += 1
    else:
        request.session['carrito'][str(producto.id)] = {
            'nombre': producto.nombre,
            'precio': str(producto.precio),
            'cantidad': 1,
            'foto': producto.foto.url if producto.foto else None,
            'subtotal': float(producto.precio),
            'inventario': producto.inventario
        }

    # Guardar el carrito en la sesión
    request.session.modified = True

    # Calcular la cantidad total de productos en el carrito
    cantidad_total = sum(item['cantidad'] for item in request.session['carrito'].values())
    messages.success(request, f"{producto.nombre} ha sido agregado al carrito.")
    
    return redirect('lista_productos')


def cancelar_pedido(request, producto_id):
    try:
        # Aquí deberías tener lógica para cancelar un pedido específico
        # Por ejemplo, si estás eliminando un producto del carrito
        detalle = DetallePedido.objects.get(producto_id=producto_id)
        detalle.delete()
        messages.success(request, "Producto cancelado correctamente.")
    except DetallePedido.DoesNotExist:
        messages.error(request, "El producto no se encontró en el pedido.")
    return redirect('lista_productos')

def cancelar_producto(request, producto_id):
    if 'carrito' in request.session:
        if str(producto_id) in request.session['carrito']:
            del request.session['carrito'][str(producto_id)]
            request.session.modified = True
            messages.success(request, "Producto cancelado del carrito.")
        else:
            messages.warning(request, "El producto no está en el carrito.")
    else:
        messages.warning(request, "El carrito está vacío.")
    return redirect('ver_carrito')


def cambiar_cantidad(request, producto_id):
    if request.method == 'POST':
        cantidad = int(request.POST.get('cantidad'))
        
        # Verificar que el producto esté en el carrito
        if 'carrito' in request.session and str(producto_id) in request.session['carrito']:
            producto = request.session['carrito'][str(producto_id)]
            
            # Limitar la cantidad a no más que el inventario disponible
            if cantidad <= producto['inventario']:
                producto['cantidad'] = cantidad
                producto['subtotal'] = float(producto['precio']) * cantidad  # Calcular el subtotal aquí
                request.session.modified = True

                # Recalcular el total del carrito
                total_carrito = 0
                for item in request.session['carrito'].values():
                    total_carrito += item['subtotal']

                messages.success(request, "Cantidad actualizada en el carrito.")
                return JsonResponse({'success': True, 'total_carrito': total_carrito})

            else:
                messages.warning(request, "La cantidad excede el inventario disponible.")
        else:
            messages.warning(request, "El producto no está en el carrito.")
    
    return JsonResponse({'success': False})





def registro(request):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if password1 != password2:
            messages.warning(request, "Las contraseñas no coinciden")
            return redirect("registro")

        if Usuario.objects.filter(email=email).exists():

miProyecto/fennys/templates/fennys/perfil/editar_perfil.html
{% extends 'fennys/barnav.html' %}
{% load static %}

{% block titulo %}Editar Perfil{% endblock %}

{% block content %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-info">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="nombre" class="form-label">Nombre:</label>
                <input type="text" class="form-control" name="nombre" value="{{ user.nombre }}" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email:</label>
                <input type="email" class="form-control" name="email" value="{{ user.email }}" required>
            </div>
            <div class="mb-3">
                <label for="cedula" class="form-label">Cédula:</label>
                <input type="number" class="form-control" name="cedula" value="{{ user.cedula }}" required>
            </div>
            <div class="mb-3">
                <label for="fechaNacimiento" class="form-label">Fecha de Nacimiento:</label>
                <input type="date" class="form-control" name="fechaNacimiento" value="{{ user.fecha_nacimiento|date:'Y-m-d' }}" required>
            </div>
            <div class="mb-3">
                <label for="foto_nueva" class="form-label">Cambiar Foto de Perfil:</label>
                <input type="file" class="form-control" name="foto_nueva">
            </div>
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>
    </div>
{% endblock %}

miProyecto/fennys/templates/fennys/perfil/ver_perfil.html
{% extends 'fennys/barnav.html' %}
{% load static %}

{% block titulo %}Mi Perfil{% endblock %}

{% block content %}
  <div class="card mb-3 mt-5 w-100 ml-0 mr-0 mx-auto" style="max-width: 700px; margin-top: 2.5em;">
    <div class="row g-0">
      <div class="col-md-4 d-flex justify-content-center align-items-center">
        {% if user.foto %}
        <img src="{{ user.foto.url }}" class="img-fluid rounded-circle" alt="Foto de perfil" style="height: 200px; margin-top: 20px;">
        {% else %}
        <img src="{% static 'fennys/img/default.png' %}" class="img-fluid rounded-circle" alt="Foto de perfil predeterminada" style="height: 200px; margin-top: 20px;">
        {% endif %}
    </div>    
      <div class="col-md-8">
        <div class="card-body">
          <div class="card-title d-flex justify-content-between">
            <h5 class="card-title fw-bold">{{ user.nombre }}</h5>
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#editarPerfil"><i class="bi bi-pencil"></i></button>
          </div>
          <p class="card-text"><small class="text-body-secondary">{{ user.get_rol_display }}</small></p>
          <p class="card-text">
            <strong>Correo:</strong> {{ user.email }} <br>
            <strong>Cédula:</strong> {{ user.cedula }} <br>
            <strong>Fecha Nacimiento:</strong> {{ user.fecha_nacimiento }}
          </p>
        </div>
        <div class="card-body">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-left: 3%; margin-right: 3%;">
                <a class="btn btn-primary" data-toggle="modal" data-target="#cambiarContrasena">Cambiar contraseña</a>
                <a href="{% url 'logout' %}" type="button" class="btn btn-danger"><i class="bi bi-box-arrow-right"></i> Cerrar sesión</a>
            </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal para editar perfil -->
<div class="modal fade" id="editarPerfil" tabindex="-1" role="dialog" aria-labelledby="editarPerfilLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="editarPerfilLabel">Editar perfil</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <form class="formulario" action="{% url 'editar_perfil' user.id %}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="mb-3">
                      <label for="nombre" class="form-label">Nombre</label>
                      <input type="text" class="form-control" id="nombre" name="nombre" value="{{ user.nombre }}" required>
                  </div>
                  <div class="mb-3">
                      <label for="cedula" class="form-label">Cédula</label>
                      <input type="number" class="form-control" id="cedula" name="cedula" value="{{ user.cedula }}" required>
                  </div>
                  <div class="mb-3">
                      <label for="email" class="form-label">Email</label>
                      <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" required>
                  </div>
                  <div class="mb-3">
                      <label for="fechaNacimiento" class="form-label">Fecha de nacimiento</label>
                      <input type="date" class="form-control" id="fechaNacimiento" name="fechaNacimiento" value="{{ user.fecha_nacimiento|date:'Y-m-d' }}" required>
                  </div>
                  <div class="mb-3">
                      <label for="foto_nueva" class="form-label">Cambiar foto de perfil</label>
                      <input class="form-control" type="file" id="foto_nueva" name="foto_nueva">
                  </div>
                  <button type="submit" class="btn btn-success">Editar Perfil</button>
              </form>
          </div>
      </div>
  </div>
</div>

<!-- Modal para cambiar contraseña -->
<div class="modal fade" id="cambiarContrasena" tabindex="-1" role="dialog" aria-labelledby="cambiarContrasenaLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="cambiarContrasenaLabel">Cambiar contraseña</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <form class="formulario" action="{% url 'cambiar_clave' %}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="mb-3">
                      <label for="clave" class="form-label">Contraseña actual</label>
                      <input type="password" class="form-control" id="clave" name="clave" required>
                  </div>
                  <div class="mb-3">
                      <label for="nueva1" class="form-label">Contraseña nueva</label>
                      <input type="password" class="form-control" id="nueva1" name="nueva1" required>
                  </div>
                  <div class="mb-3">
                      <label for="nueva2" class="form-label">Repetir contraseña</label>
                      <input type="password" class="form-control" id="nueva2" name="nueva2" required>
                  </div>
                  <button type="submit" class="btn btn-success">Cambiar contraseña</button>
              </form>
          </div>
      </div>
  </div>
</div>

{% endblock %}